boot-strap: add clone cleanup and cmdline opts
Signed-off-by: Armin Kuster <akuster808@gmail.com>

diff --git a/boot-strap b/boot-strap
--- a/boot-strap
+++ b/boot-strap
@@ -5,6 +5,8 @@
 #############################################################################
 #
 
+CLONE_DIR="summit-setup"
+
 # Print error information and exit.
 echo_error () {
   echo "ERROR: $1" >&2
@@ -17,8 +19,7 @@ get_os_type() {
   then
     os_type=`grep '^NAME=\"' /etc/os-release | awk -F "\"" '{print tolower($2)}' | awk -F " " '{print $1}'`
   else
-    echo "Error: Check terminated on unsupported operating system type."
-    exitCode=1
+    echo_error "Error: Check terminated on unsupported operating system type."
   fi
 }
 
@@ -28,17 +29,21 @@ bootstrap_host () {
 
   get_os_type
 
-  # run host specific setup scripts
+  # run host specific boot strap setup scripts
   $(pwd -P)/scripts/$os_type-bootstrap
 }
 
 clone_setup () {
-   git clone https://github.com/akuster/summit-setup.git
+  if [ -d $CLONE_DIR ];
+  then
+     rm -fr $CLONE_DIR
+  fi
+
+  git clone https://github.com/akuster/summit-setup.git $CLONE_DIR
 }
 
 run_setup() {
-  cd summit-setup
-  setup-host
+  sh setup-host -u USERNAME $1
 }
 
 
@@ -53,10 +58,35 @@ Options:
 EOF
 }
 
+
+while getopts "u:h" OPT; do
+  case $OPT in
+    u)
+      USERNAME="$OPTARG"
+    ;;
+    h)
+      description
+      exit 0
+    ;;
+
+    *) echo "Invalid option specified: $*"
+      echo_error "Usage: $0 [-h|-help]"
+    ;;
+  esac
+done
+
+if [ -z "$USERNAME" ]; then
+  echo "ERROR: you must specify an intial user account ."
+  usage
+  exit 1
+fi
+
+
 #====
 
-bootstrap_host
 clone_setup
-run_setup
+cd $CLONE_DIR
+bootstrap_host
+uun_setup $USERNAME
 
 #====
